# Generated by Django 4.2.6 on 2023-11-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Current Date')),
                ('box', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1)),
                ('genre', models.CharField(choices=[('PO', 'Pop'), ('PH', 'Pop Heroes'), ('PA', 'Pop Animation'), ('PC', 'Pop Comics'), ('PM', 'Pop Movies'), ('PT', 'Pop Television')], default='PO', max_length=2)),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pop')),
            ],
        ),
    ]
