# Generated by Django 4.2.6 on 2023-11-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_logging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logging',
            old_name='box',
            new_name='opened',
        ),
    ]
