# Generated by Django 4.2.6 on 2023-11-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_box_logging_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logging',
            options={'ordering': ['-date']},
        ),
    ]
