# Generated by Django 4.2.6 on 2023-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_logging_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pop',
            name='partners',
            field=models.ManyToManyField(to='main_app.partner'),
        ),
    ]
